# Generated by Django 4.0.3 on 2022-03-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registro',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('created_at', models.DateField()),
                ('amount_products', models.IntegerField()),
            ],
        ),
    ]
