# Generated by Django 4.0.3 on 2022-03-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFornecedores',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('created_at', models.DateField()),
                ('amount_products', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='registro',
        ),
    ]
